# Generated by Django 3.1.7 on 2021-04-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210402_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinehistory',
            old_name='medicine_hame',
            new_name='medicine_name',
        ),
    ]
