# Generated by Django 3.1.7 on 2021-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinehistory',
            name='end_date',
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='lasting_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lasting_day',
            field=models.IntegerField(default=0),
        ),
    ]
