# Generated by Django 3.1.7 on 2021-04-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210404_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
