# Generated by Django 3.1.7 on 2021-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_fitbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('distance', models.FloatField()),
                ('floors', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('exercise_minutes', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
